apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: guestbook
  name: my-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app
